name: chime
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # for using cupertino icons
  cupertino_icons: ^1.0.6

  # for integrating firebase
  firebase_core: ^3.6.0

    # For handling firebase authentication
  firebase_auth: ^5.0.0

  # For handling google sign in
  google_sign_in: ^6.2.1

    # For accessing cloud firestore database
  cloud_firestore: ^5.0.0

  # for accessing cached network image
  cached_network_image: ^3.4.1

  # For picking images
  image_picker: ^1.1.2

  # For accessing Firebase Storage (for uploading files)
  firebase_storage: ^12.0.0

  # for emojis
  emoji_picker_flutter: ^3.1.0
  # for using firegase push notifications
  firebase_messaging: ^15.1.5

    # For storing images into gallery
  gallery_saver_updated: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# for flutter packages specifically
flutter:

  # for using material icons
  uses-material-design: true

  assets:
    - assets/images/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
