// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_vvstLV7u0_JB1VvD6e686FLyjJI9pXo',
    appId: '1:63911203389:android:a94f611fc9196d69e19054',
    messagingSenderId: '63911203389',
    projectId: 'chime-flutter-app',
    storageBucket: 'chime-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABpfLELmd2byYwCRMKvQD-qaUTSDwAp-g',
    appId: '1:63911203389:ios:e19263f5253d81cfe19054',
    messagingSenderId: '63911203389',
    projectId: 'chime-flutter-app',
    storageBucket: 'chime-flutter-app.appspot.com',
    androidClientId: '63911203389-4vuc2jh317h506qt4u0t2i9vq9pkvedi.apps.googleusercontent.com',
    iosClientId: '63911203389-p1snc8b7b7ohc43kjt1ibtnjumu92p68.apps.googleusercontent.com',
    iosBundleId: 'com.example.chime',
  );

}